spring.application.name=ForumHub

spring.datasource.url=jdbc:mysql://localhost/forum_hub
spring.datasource.username=root
spring.datasource.password=${DB_SQL_SENHA}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=12345678